# Nombre del microservicio y PUERTO (Vital para que no choque con el inventario)
spring.application.name=orders-api
server.port=8081

# Base de datos H2 independiente para las órdenes
spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true